"use client"
import { Fragment, useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { NfeImportModal } from './NfeImportModal'
import { getNotaCompleta, type NotaCompletaResultado } from '@/app/financeiro/dre/cmv/actions'
export type DocumentoSaida = { chave: string; numero: string | null; emissao: string | null; valor_total: number | null; destinatario_nome: string | null; emitente_nome: string | null }
const fmt = (v: number) => new Intl.NumberFormat('pt-BR', {style:'currency',currency:'BRL'}).format(v)
const box = {background:'var(--surface)',border:'1px solid var(--border)',borderRadius:10,padding:16}
const control = {padding:'9px 14px',border:'1px solid var(--border)',borderRadius:8,background:'var(--surface)',color:'var(--text)'}
export function NfeSaidaClient({notas,meses,mes,ano,pagina,quantidade,total,q}: {notas:DocumentoSaida[];meses:string[];mes:number;ano:number;pagina:number;quantidade:number;total:number;q:string}) {
 const router=useRouter(); const [pending,startTransition]=useTransition(); const [importar,setImportar]=useState(false); const [busca,setBusca]=useState(q)
 const [aberta,setAberta]=useState<string|null>(null); const [detalhes,setDetalhes]=useState<Record<string,NotaCompletaResultado>>({}); const [erro,setErro]=useState<string|null>(null)
 function navegar(m=mes,a=ano,p=1,b=busca) {startTransition(()=>router.push(`/financeiro/dre/nfe-saida?${new URLSearchParams({mes:String(m),ano:String(a),pagina:String(p),q:b})}`))}
 async function abrir(chave:string) {setAberta(aberta===chave?null:chave);setErro(null); if(detalhes[chave])return;try {const d=await getNotaCompleta(chave);if(!d.nota)throw new Error('Não foi possível carregar a nota.');setDetalhes(v=>({...v,[chave]:d}))}catch(e){setErro(String(e))}}
 return <div style={{maxWidth:1400,margin:'0 auto',color:'var(--text)'}}>
 <div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap',marginBottom:24}}><div><h1 style={{fontSize:28,fontWeight:700,margin:"0 0 8px"}}>NF-e Saída</h1><p style={{color:'var(--text-3)'}}>Notas emitidas · itens carregados ao abrir a nota</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><select aria-label="Mês" value={`${ano}-${String(mes).padStart(2,'0')}`} style={control} disabled={pending} onChange={e=>{const[a,m]=e.target.value.split('-').map(Number);navegar(m,a)}}>{meses.map(m=><option key={m} value={m}>{m.slice(5)}/{m.slice(0,4)}</option>)}</select><button style={control} onClick={()=>setImportar(true)}>Importar NF-e Saída</button></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginBottom:20}}><div style={box}>Total das notas{q?' encontradas':''}<div style={{fontSize:26,fontWeight:700,margin:"8px 0"}}>{fmt(total)}</div><small>Valor fiscal (vNF), excluindo canceladas</small></div><div style={box}>Notas{q?' encontradas':''}<div style={{fontSize:26,fontWeight:700,margin:"8px 0"}}>{quantidade.toLocaleString('pt-BR')}</div></div></div>
 <form onSubmit={e=>{e.preventDefault();navegar()}} style={{display:'flex',gap:8,marginBottom:16}}><input aria-label="Buscar notas" placeholder="Número, emitente ou destinatário" style={{...control,flex:1}} value={busca} onChange={e=>setBusca(e.target.value)}/><button style={control} disabled={pending}>Buscar</button></form>
 {pending&&<p role="status">Carregando notas…</p>}
 <div style={{...box,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{['Nota','Emissão','Emitente','Destinatário','Valor'].map(x=><th key={x} style={{textAlign:'left',padding:10}}>{x}</th>)}</tr></thead><tbody>{notas.map(n=><Fragment key={n.chave}><tr style={{borderTop:'1px solid var(--border)'}}><td style={{padding:10}}><button style={control} aria-expanded={aberta===n.chave} onClick={()=>abrir(n.chave)}>{aberta===n.chave?'−':'+'} {n.numero}</button></td><td>{n.emissao?new Date(n.emissao).toLocaleDateString('pt-BR'):'—'}</td><td>{n.emitente_nome}</td><td>{n.destinatario_nome??'Não informado'}</td><td style={{whiteSpace:'nowrap'}}>{fmt(Number(n.valor_total??0))}</td></tr>{aberta===n.chave&&<tr><td colSpan={5} style={{padding:16,background:'var(--surface-2)'}}>{erro?<p role="alert">{erro}</p>:!detalhes[n.chave]?<p>Carregando itens…</p>:<><p>Chave: {n.chave}</p><table style={{width:'100%'}}><thead><tr><th>Produto</th><th>Quantidade</th><th>Unidade</th><th>Valor</th></tr></thead><tbody>{detalhes[n.chave]!.itens.map((item,i)=><tr key={i}><td>{item.itemDescricao}</td><td style={{textAlign:'center'}}>{item.quantidade}</td><td style={{textAlign:'center'}}>{item.unidade}</td><td style={{textAlign:'right'}}>{fmt(Number(item.valorTotal??0))}</td></tr>)}</tbody></table></>}</td></tr>}</Fragment>)}{notas.length===0&&<tr><td colSpan={5} style={{padding:24}}>Nenhuma nota encontrada.</td></tr>}</tbody></table></div>
 <div style={{display:'flex',gap:16,alignItems:'center',justifyContent:'flex-end',marginTop:16}}><button disabled={pending||pagina<=1} style={control} onClick={()=>navegar(mes,ano,pagina-1)}>Anterior</button><span>Página {pagina} de {Math.max(1,Math.ceil(quantidade/50))}</span><button disabled={pending||pagina*50>=quantidade} style={control} onClick={()=>navegar(mes,ano,pagina+1)}>Próxima</button></div>
 {importar&&<NfeImportModal direction="saida" onClose={()=>setImportar(false)} onSuccess={()=>{setImportar(false);router.refresh()}}/>}
 </div>
}
